apiVersion: v1
kind: Pod
metadata:
  name: cloudsmith-demo-pod
  namespace: default
spec:
  containers:
  - name: demo-container
    image: docker.cloudsmith.io/CLOUDSMITH_ORG/CLOUDSMITH_REPO/ubuntu:latest
    command: ["sleep", "3600"]  # Sleep for 1 hour, just as an example
  imagePullSecrets:
  - name: cloudsmith-registry-secret